### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by twist3dimages** [traefik/traefik#11099]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I have noticed lately Traefik keeps restarting on Unraid. Starting yesterday, it just keeps restarting with the logs below

### What did you see instead?

Constant container restarting. However, I have another server running the same version and it doesn't error out.

### What version of Traefik are you using?

 3.1.3

### What is your environment & configuration?

global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  cd1git-wg:
    address: ":55082/udp"
  metrics:
    address: ":8082"
  # Not used in apps, but redirect everything from HTTP to HTTPS
  traefikhub-api:
   address: ":9900"
  traefikhub-tunl:
   address: ":9901"
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
      # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32

        # Trusted IPs
     #   - 192.168.50.0/24
        # - 172.18.0/16
        # End of Cloudlare public IP list
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    forwardedHeaders:
  # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: domain.com
            sans:
              - '*.domain.com'
      middlewares:
        - "securityHeaders@file"
        - "crowdsec-bouncer@file"

providers:
  providersThrottleDuration: 2s
  # File provider for connecting things that are outside of docker / defining middleware
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: proxy# Add Your Docker Network Name Here
    # Default host rule to containername.domain.example
    defaultRule: 'Host(`{{ lower (trimPrefix `/` .Name )}}.domain.com`)' # Replace with your domain
  #  swarmModeRefreshSeconds: 15s
    exposedByDefault: false
    endpoint: "tcp://dockersocket:2375"
   # swarmMode: false

# Enable traefik ui
api:
  dashboard: true
  insecure: true

#
log:
  level: DEBUG

# Use letsencrypt to generate ssl serficiates
certificatesResolvers:
  letsencrypt:
    acme:
      email: <emaill>
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'
  tailscale:
    tailscale: {}
   

hub:
  tls:
    insecure: true

accessLog:
  filePath: '/etc/traefik/access.log'
  bufferingSize: 50
  format: json

### If applicable, please paste the log output in DEBUG level

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x45249fa]
all values are hidden
goroutine 1 [running]:
github.com/traefik/traefik/v3/pkg/server.NewRouterFactory({0xc001dac0b4, 0xc001bfdc00, 0xc001dd23c0, 0xc001daeb70, 0xc001a68c60, 0xc001e2c630, 0x0, 0x0, 0xc001a37500, 0xc001df6440, ...}, ...)
	github.com/traefik/traefik/v3/pkg/server/routerfactory.go:46 +0xba
main.setupServer(0xc001a68bd0)
	github.com/traefik/traefik/v3/cmd/traefik/traefik.go:291 +0x1085
main.runCmd(0xc001a68bd0)
	github.com/traefik/traefik/v3/cmd/traefik/traefik.go:117 +0x2b4
main.main.func1({0xc001dd23e0?, 0xc000248080?, 0xc00121fd98?})
	github.com/traefik/traefik/v3/cmd/traefik/traefik.go:65 +0x19
github.com/traefik/paerser/cli.run(0xc0014c3280, {0xc000248080, 0x0?, 0x0})
	github.com/traefik/paerser@v0.2.1/cli/commands.go:133 +0x243
github.com/traefik/paerser/cli.execute(0xc0014c3280, {0xc000248080, 0x2, 0x2}, 0x68?)
	github.com/traefik/paerser@v0.2.1/cli/commands.go:76 +0x6cf
github.com/traefik/paerser/cli.Execute(...)
	github.com/traefik/paerser@v0.2.1/cli/commands.go:51
main.main()
	github.com/traefik/traefik/v3/cmd/traefik/traefik.go:81 +0x53b
09/18/2024
12:01:28 PM
Container stopped

**Comment by twist3dimages** [comment]
It looks like it's the tailscale configuration that is messing it up. I followed the docs, what should i put instead?

**Comment by kevinpollet** [comment]
Closed by https://github.com/traefik/traefik/pull/11103
