### ISSUE TITLE
Improve Traefik Documentation

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#11163]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello,

I'm creating this issue to keep track of our upcoming efforts on the documentation.

The new structure will consist of two main sections:

- A step-by-step guide designed to assist new users on their Traefik journey.
- A reorganized reference documentation that includes detailed descriptions for every option.

We'll begin with restructuring the reference documentation before we move on to the user guides

We'd love your help in making the documentation better and more useful for you.
Please share your comments, feedback, or open PRs — your input is always welcome!

**Comment by audas** [comment]
Hi - new user here of Docker, Traefik - everything. Came here out of frustration with Apache2 and Nginx.
I followed your documentation for an Ubuntu set up from https://awesome.traefik.io/. which led me to here https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-16-04

With this failing with panic - it was wildly out of my league to understand this error.

**
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/containous/traefik/vendor/github.com/miekg/dns.ClientConfigFromFile(0x1fa9acf, 0x10, 0x0, 0x0, 0x0)
        /go/src/github.com/containous/traefik/vendor/github.com/miekg/dns/clientconfig.go:86 +0x948
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.getNameservers(0x1fa9acf, 0x10, 0x2ea4c40, 0x2, 0x2, 0xc420068280, 0xc420191f58, 0x76333e)
        /go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
github.com/containous/traefik/vendor/github.com/xenolf/lego/acme.init()
        /go/src/github.com/containous/traefik/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
github.com/containous/traefik/acme.init()
        /go/src/github.com/containous/traefik/acme/localStore_unix.go:26 +0x7f
main.init()
        /go/src/github.com/containous/traefik/cmd/traefik/version.go:64 +0xac

**


Went back to the Digital Ocean tutorial and checked the date - 2017. Sigh. 

Not even a valid docker tutorial?

Where to go though?

**Comment by kevinpollet** [comment]
Hello @audas and thanks for raising this,

You are right the link is outdated and we disabled the wiki to avoid such confusion.
Here is a link to our Docker tutorial available in the Traefik documentation: https://doc.traefik.io/traefik/getting-started/quick-start/

For questions related to Traefik, you can use the community [forum](https://community.traefik.io/c/traefik/5) and obtain help from the community.

**Comment by audas** [comment]
I spent several days trying to implement Traefik on a home network behind a static IP and could not get it to work. 

There is no documentation or support for this and every request for help or guidance on this issue is met with - use domain names. 

So much so that one of the most common responses on searches for this issue is about the fact there is no support for IP only behind static IPs.

Maybe its just not doable. If not - maybe just say that in the new documentation.

**Comment by nmengin** [comment]
Hey @audas,

Could you please open a dedicated issue for this error, with a scenario and manifests that allow us to reproduce the issue?

Thanks in advance.
