### ISSUE TITLE
Traefik keeps running out of memory

### ISSUE THREAD

**Issue by PeterBurner** [traefik/traefik#4770]
### Do you want to request a *feature* or report a *bug*?

Bug

### Did you try using a 1.7.x configuration for the version 2.0?

- [ ] Yes
- [x] No

### What did you do?

We are using Traefik version 1.7.10. Our config provider is DynamoDB. We have approximately 12.000 Frontends and Backends. Traefik currently runs on a `t3.medium` in AWS. For our config file see below.

### What did you expect to see?

Since we are trying to use Traefik as a reverse proxy for 12.000 devices we expected it to consume much resources. Hence we hoped a rather large AWS instance would do the trick.  
When Traefik starts it should load all backends and frontends into the memory. They should be kept up-to-date but the memory usage should stay pretty much constant.

### What did you see instead?

Unfortunately every time Traefik loads the data from DynamoDB the RAM consumption increases very much. We confirmed that this update procedure is causing the increase by modifying the config parameter `refreshSeconds` for the DynamoDB provider. Eventually the machine runs out of free memory and becomes unresponsive.  
#### Refresh time is 1h
![1h](https://user-images.githubusercontent.com/15011953/56124381-d07ad000-5f76-11e9-8074-b2bc6ba31565.png)  
#### Refresh time is 5min
![5min](https://user-images.githubusercontent.com/15011953/56124675-73334e80-5f77-11e9-9fdc-e7a12bd08f7b.png)  

As one can see in the second graph, sometimes Traefik itself crashes due to a lack of memory even before the instance is killed by AWS. For log snippets see below.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.10
Codename:     maroilles
Go version:   go1.11.6
Built:        2019-03-29_12:20:34PM
OS/Arch:      linux/amd64
```

#### Config
```toml
checkNewVersion = false
logLevel = "INFO"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.traefik-dashboard]
    address = ":8080"

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.whiteList]
      sourceRange = ["10.0.0.0/16"]

[api]
  dashboard = false
  entryPoint = "traefik-dashboard"

[dynamodb]
  region = "eu-central-1"
  tableName = "proxy-subdomains"
  watch = true
  refreshSeconds = 3600
```

#### Backend
```json
{
  "backend": {
    "circuitbreaker": {
      "expression": "NetworkErrorRatio() > 0.5"
    },
    "maxconn": {
      "amount": 10,
      "extractorfunc": "request.host"
    },
    "servers": {
      "device": {
        "url": "http:// ..."
      }
    }
  },
  "id": "backend-1",
  "name": "device-1",
  "type": "backend"
}
````

#### Frontend
```json
{
  "alias": [
    "device-name"
  ],
  "frontend": {
    "backend": "device-1",
    "errors": {
      "network": {
        "backend": "error",
        "query": "/error",
        "status": [
          "500-599"
        ]
      }
    },
    "routes": {
      "paths": {
        "rule": "PathPrefix:/health,/access_token,/webapp,/api"
      },
      "subdomains": {
        "rule": "Host:device-1.our-domain.de"
      }
    }
  },
  "id": "frontend-1",
  "mac": "XXXXXXXXXXXX",
  "name": "device-1",
  "registered": "timestamp",
  "serial": 1,
  "type": "frontend"
}
```

#### Without DEBUG

<details>
<summary>logs</summary>

```
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: bufio.(*Reader).Peek(0xc0fc210c60, 0x1, 0x0, 0x0, 0x1, 0xc0001c19e0, 0x0)
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: /usr/local/go/src/bufio/bufio.go:132 +0x3f
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: net/http.(*persistConn).readLoop(0xc0c4adcfc0)
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: /usr/local/go/src/net/http/transport.go:1645 +0x1a2
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: created by net/http.(*Transport).dialConn
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: /usr/local/go/src/net/http/transport.go:1338 +0x941
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: goroutine 1611 [select, 1 minutes]:
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: github.com/containous/traefik/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc0d340b8d0, 0xc0059f1500)
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: /go/src/github.com/containous/traefik/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0xd5
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: created by github.com/containous/traefik/vendor/github.com/patrickmn/go-cache.runJanitor
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal traefik[7108]: /go/src/github.com/containous/traefik/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xa9
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal systemd[1]: traefik.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal systemd[1]: Unit traefik.service entered failed state.
Apr 01 11:21:35 ip-10-0-30-22.eu-central-1.compute.internal systemd[1]: traefik.service failed.
```
#### With DEBUG
```
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/server/server_signals.go:18 +0xbc
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/server.(*Server).Start.func3(0xc00018e230)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/server/server.go:259 +0x34
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.(*Pool).Go.func1()
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:78 +0x37
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.GoWithRecover.func1(0x2848a00, 0xc0002d9a10)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/safe.GoWithRecover
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 32 [chan receive, 10 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/provider/dynamodb.(*Provider).Provide.func2.1()
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/provider/dynamodb/dynamodb.go:164 +0x3c
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.GoWithRecover.func1(0x2848a00, 0xc0003d9560)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/safe.GoWithRecover
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 45 [select, 1 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/server.(*Server).throttleProviderConfigReload(0xc0003ee000, 0x77359400, 0xc0000849c0, 0xc0000b07e0, 0xc00a138000)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/server/server_configuration.go:459 +0x1e6
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/server.(*Server).preLoadConfiguration.func1(0xc00a138000)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/server/server_configuration.go:328 +0x4f
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.(*Pool).Go.func1()
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:78 +0x37
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.GoWithRecover.func1(0x2848a00, 0xc0087b2180)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/safe.GoWithRecover
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 46 [select, 1 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/vendor/github.com/eapache/channels.(*RingChannel).ringBuffer(0xc0087b21e0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/vendor/github.com/eapache/channels/ring_channel.go:87 +0x205
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/vendor/github.com/eapache/channels.NewRingChannel
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/vendor/github.com/eapache/channels/ring_channel.go:32 +0x1cc
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 47 [select]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/server.(*Server).throttleProviderConfigReload.func1(0xc002653960)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/server/server_configuration.go:446 +0xd9
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.(*Pool).Go.func1()
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:78 +0x37
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/safe.GoWithRecover.func1(0x2848a00, 0xc0087b2210)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/safe.GoWithRecover
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 188 [select, 1 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc0def3a9e0, 0xc00c9e0140)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0xd5
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/vendor/github.com/patrickmn/go-cache.runJanitor
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xa9
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 187 [select, 1 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: github.com/containous/traefik/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc0def3a9d0, 0xc00c9e0080)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0xd5
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by github.com/containous/traefik/vendor/github.com/patrickmn/go-cache.runJanitor
Apr 15 08:27:06 ip-10-0-63-244 traefik: /go/src/github.com/containous/traefik/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xa9
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 197 [IO wait, 1 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: internal/poll.runtime_pollWait(0x7f77c2fd3bc0, 0x72, 0xc0007c5858)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/runtime/netpoll.go:173 +0x66
Apr 15 08:27:06 ip-10-0-63-244 traefik: internal/poll.(*pollDesc).wait(0xc0fac0b598, 0x72, 0xffffffffffffff00, 0x2a9a580, 0x44815d8)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
Apr 15 08:27:06 ip-10-0-63-244 traefik: internal/poll.(*pollDesc).waitRead(0xc0fac0b598, 0xc0fc128000, 0x2000, 0x2000)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Apr 15 08:27:06 ip-10-0-63-244 traefik: internal/poll.(*FD).Read(0xc0fac0b580, 0xc0fc128000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
Apr 15 08:27:06 ip-10-0-63-244 traefik: net.(*netFD).Read(0xc0fac0b580, 0xc0fc128000, 0x2000, 0x2000, 0x408bbb, 0xc000038000, 0x2327940)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/fd_unix.go:202 +0x4f
Apr 15 08:27:06 ip-10-0-63-244 traefik: net.(*conn).Read(0xc0fa648048, 0xc0fc128000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/net.go:177 +0x68
Apr 15 08:27:06 ip-10-0-63-244 traefik: crypto/tls.(*block).readFromUntil(0xc0fc0a1650, 0x2a97640, 0xc0fa648048, 0x5, 0xc0fa648048, 0x44b99a)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/crypto/tls/conn.go:492 +0x89
Apr 15 08:27:06 ip-10-0-63-244 traefik: crypto/tls.(*Conn).readRecord(0xc0004b9c00, 0x284e117, 0xc0004b9d20, 0x4595d0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/crypto/tls/conn.go:593 +0xdd
Apr 15 08:27:06 ip-10-0-63-244 traefik: crypto/tls.(*Conn).Read(0xc0004b9c00, 0xc0fbe26000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
Apr 15 08:27:06 ip-10-0-63-244 traefik: net/http.(*persistConn).Read(0xc0c507d560, 0xc0fbe26000, 0x1000, 0x1000, 0xc0007c5c70, 0x404cd5, 0xc0000b1080)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/http/transport.go:1497 +0x75
Apr 15 08:27:06 ip-10-0-63-244 traefik: bufio.(*Reader).fill(0xc0fbc6b4a0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/bufio/bufio.go:100 +0x10f
Apr 15 08:27:06 ip-10-0-63-244 traefik: bufio.(*Reader).Peek(0xc0fbc6b4a0, 0x1, 0x0, 0x0, 0x1, 0xc0000b1e00, 0x0)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/bufio/bufio.go:132 +0x3f
Apr 15 08:27:06 ip-10-0-63-244 traefik: net/http.(*persistConn).readLoop(0xc0c507d560)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/http/transport.go:1645 +0x1a2
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by net/http.(*Transport).dialConn
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/http/transport.go:1338 +0x941
Apr 15 08:27:06 ip-10-0-63-244 traefik: goroutine 198 [select, 1 minutes]:
Apr 15 08:27:06 ip-10-0-63-244 traefik: net/http.(*persistConn).writeLoop(0xc0c507d560)
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/http/transport.go:1885 +0x113
Apr 15 08:27:06 ip-10-0-63-244 traefik: created by net/http.(*Transport).dialConn
Apr 15 08:27:06 ip-10-0-63-244 traefik: /usr/local/go/src/net/http/transport.go:1339 +0x966
Apr 15 08:27:06 ip-10-0-63-244 systemd: traefik.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 15 08:27:06 ip-10-0-63-244 systemd: Unit traefik.service entered failed state.
Apr 15 08:27:06 ip-10-0-63-244 systemd: traefik.service failed.
```

</details>

**Comment by PeterBurner** [comment]
I tried to recreate our setup with the file provider. As one can see in the graph below, with this provider there is only a little spike when making changes to the config file.
<img width="1073" alt="file_provider" src="https://user-images.githubusercontent.com/15011953/56138063-5b1ef780-5f96-11e9-8e9a-9e40a1a1d740.png">

**Comment by PeterBurner** [comment]
OK, I take back what I said in my last comment. It only applies if I make some random changes in the rules.toml by hand. I wrote a node script that once per minute pulls all changes from DynamoDB and writes them into the rules.toml and gues what happens:
<img width="593" alt="grafik" src="https://user-images.githubusercontent.com/15011953/56269446-f2e62800-60f3-11e9-9ee4-7fac0f91fc86.png">
In our system everytime a backend device looses its connection and reconnects the URL changes. This happens for approx. 30 devices every minute (remeber we have 12000 devices in total).
I modified the script to use some random data instead of DynamoDB so you should be able to reproduce it:
[index.js.zip](https://github.com/containous/traefik/files/3088446/index.js.zip)

**Comment by PeterBurner** [comment]
I can also reproduce this problem with Traefik 2.0.0-alpha.  
![image](https://user-images.githubusercontent.com/15011953/58160758-5fb68a00-7c7f-11e9-987f-1e3448212cc9.png)  
There it behaves a little bit different. First it slowly rises step by step to ~40% (1.5GB) and then it stays at that. Only when I put some traffic on the server the memory consumption rises further until nothing is left.

**Comment by rtribotte** [comment]
Hello,

This issue was for the v1, but as described in our [deprecation notices](https://doc.traefik.io/traefik/deprecation/releases/) the v1 is not supported anymore.
Accordingly, we are closing this issue.
