### ISSUE TITLE
Panic when deregistering backends

### ISSUE THREAD

**Issue by madsholden** [traefik/traefik#7551]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Redeploy backend service. New instances of the backend are started, and registered in Consul. When they are healthy, the old instances start returning 500 on health checks, and after a while remove themselves from Consul.

### What did you expect to see?

All requests being routed to healthy backend instances.

### What did you see instead?

One request went to an unhealthy backend, which returned a 500. The application logs show that this backend service started failing health checks 10 seconds before this request. The traefik logs show three errors, pasted below.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.0
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-23T10:55:07Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

The docker image `traefik:v2.3.0`

Config:
```
--providers.consulcatalog=true
--providers.consulcatalog.prefix=traefik
--providers.consulcatalog.constraints=Tag(`traefik-service`)
--providers.consulcatalog.refreshinterval=500ms
--entrypoints.alb.address=:${alb_port}
--entrypoints.traefik.address=:${api_port}
--ping=true
--api.dashboard=true
--log.format=json
--log.level=INFO
--accesslog=true
--accesslog.format=json
--accesslog.fields.headers.names.X-Amzn-Trace-Id=keep
--metrics.prometheus=true
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

I do not know the order of the following three messages.

```
Error in Go routine: runtime error: index out of range [4] with length 4

Stack: goroutine 97 [running]:
runtime/debug.Stack(0xc0000f0000, 0x34c682f, 0x17)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x3230d60, 0xc0027acb80)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:66 +0xb4
github.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1.1(0xc0013bbdc0)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:74 +0x56
panic(0x3230d60, 0xc0027acb80)
	/usr/local/go/src/runtime/panic.go:969 +0x175
github.com/traefik/traefik/v2/pkg/provider/consulcatalog.(*Provider).getConsulServicesData(0xc00037cae0, 0x39ead00, 0xc000125b40, 0x0, 0x1, 0x47, 0xc000f86140, 0x0)
	/go/src/github.com/traefik/traefik/pkg/provider/consulcatalog/consul_catalog.go:177 +0x7c5
github.com/traefik/traefik/v2/pkg/provider/consulcatalog.(*Provider).Provide.func1.1(0xc001a29db0, 0xc001a29db0)
	/go/src/github.com/traefik/traefik/pkg/provider/consulcatalog/consul_catalog.go:119 +0x29e
github.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1(0x0, 0x0)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:78 +0x5a
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc000205cd0, 0x7fae44a1ab18, 0xc0004a6560, 0xc0013bbf40, 0x39cc7c0, 0xc0001cd0f8, 0x0, 0x0)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:52 +0x102
github.com/cenkalti/backoff/v4.RetryNotify(...)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:31
github.com/traefik/traefik/v2/pkg/provider/consulcatalog.(*Provider).Provide.func1(0x39ead00, 0xc000125b40)
	/go/src/github.com/traefik/traefik/pkg/provider/consulcatalog/consul_catalog.go:141 +0x2e9
github.com/traefik/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:36 +0x64
github.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1(0x35d7800, 0xc0004a6540)
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:59 +0x4f
created by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover
	/go/src/github.com/traefik/traefik/pkg/safe/routine.go:53 +0x49

Provider connection error panic in operation: %!w(<nil>), retrying in 614.590364ms

```

**Comment by traefiker** [comment]
Closed by #7558.
