### ISSUE TITLE
Error in Go routine: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Lincoln-dac** [traefik/traefik#7608]
### Do you want to request a *feature* or report a *bug*?
I deploy traefik 2.27 in  my k8s cluster but ,traefik auto restart 

logs

```
time="2020-12-02T15:26:50+08:00" level=error msg="Error in Go routine: runtime error: invalid memory address or nil pointer dereference"
time="2020-12-02T15:26:50+08:00" level=error msg="Stack: goroutine 135 [running]:\nruntime/debug.Stack(0xc000258000, 0x28d681e, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24**** +0x9d\ngithub.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x242c7e0, 0x477fba0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:66 +0xb1\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x29cd138)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:56 +0x57\npanic(0x242c7e0, 0x477fba0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/containous/traefik/v2/pkg/metrics.(*prometheusState).ListenValueUpdates(0xc000c88000)\n\t/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:278 +0xc0\ngithub.com/containous/traefik/v2/pkg/metrics.initStandardRegistry.func1()\n\t/go/src/github.com/containous/traefik/pkg/metrics/prometheus.go:101 +0x2d\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x29cd138, 0x29ccff8)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:59 +0x4f\ncreated by github.com/containous/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:53 +0x49\n"
time="2020-12-02T15:27:18+08:00" level=info msg="I have to go..."
time="2020-12-02T15:27:18+08:00" level=info msg="Stopping server gracefully"
time="2020-12-02T15:27:18+08:00" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-12-02T15:27:18+08:00" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2020-12-02T15:27:18+08:00" level=error msg="accept tcp [::]:8082: use of closed network connection" entryPointName=metrics
time="2020-12-02T15:27:18+08:00" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2020-12-02T15:27:18+08:00" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2020-12-02T15:27:18+08:00" level=error msg="close tcp [::]:8082: use of closed network connection" entryPointName=metrics
time="2020-12-02T15:27:18+08:00" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2020-12-02T15:27:18+08:00" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-12-02T15:27:28+08:00" level=info msg="Server stopped"
time="2020-12-02T15:27:28+08:00" level=info msg="Shutting down"
time="2020-12-02T15:27:29+08:00" level=info msg="Traefik version 2.2.7 built on 2020-07-20T17:06:02Z"
```

Bug

### What did you do?
 traefik 2.2.7  start args
```
      - args:
        - --api.insecure
        - --api.dashboard
        - --api.debug=true
        - --log
        - --log.level=INFO
        - --log.filepath=/var/log/traefik.log
        - --accesslog=true
        - --accesslog.bufferingsize=500
        - --accesslog.filepath=/var/log/traefik-access.log
        - --accesslog.fields.names.StartUTC=drop
        - --accesslog.fields.headers.defaultmode=keep
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
        - --metrics.prometheus=true
        - --ping=true
        - --metrics.prometheus.entrypoint=metrics
        - --entryPoints.metrics.address=:8082
        - --providers.kubernetesingress.disablepasshostheaders=true
        - --providers.kubernetescrd
        - --providers.kubernetesingress=true
```

how  fix?

**Comment by ldez** [comment]
Hello,

could you try to update your Traefik to the latest stable version (v2.3.4).

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
