### ISSUE TITLE
DOMException: The operation is insecure. when https://pilot.traefik.io is blocked by the web browser

### ISSUE THREAD

**Issue by FieteO** [traefik/traefik#7641]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I have blocked third party cookies in my Firefox browser. I then accessed the webui of a self-hosted Traefik instance.

### What did you expect to see?
The website without any errors.

### What did you see instead?
The website with a frequently popping up (like once a second) "An unexpected error has occured". Also the browser console window prints out a constant stream of "DOM Exception: The operation is insecure" (like twice a second)

![Traefik_browser_console](https://user-images.githubusercontent.com/41323592/101619380-7e23d800-3a13-11eb-8911-6bcb588b8667.PNG)

Allowing `https://pilot.traefik.io` resolves the issue.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Codename:     picodon
Go version:   go1.15.2
Built:        2020-09-29T15:49:06Z
OS/Arch:      linux/amd6
```

**Comment by Dennis14e** [comment]
Same in Google Chrome:

```
instrument.js:109 DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at i (https://pilot.traefik.io/_next/static/chunks/pages/_app-b57f368bad1d2dc7294f.js:1:4015)
    at https://pilot.traefik.io/_next/static/chunks/pages/_app-b57f368bad1d2dc7294f.js:1:4211
    at Oi (https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:116993)
    at KqkS.t.unstable_runWithPriority (https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:4693)
    at jl (https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:56980)
    at Ti (https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:116454)
    at https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:116365
    at F (https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:3752)
    at MessagePort.KqkS.k.port1.onmessage (https://pilot.traefik.io/_next/static/chunks/framework.f30ca4b53ab2846e3a57.js:1:2474)
```

**Comment by kevinpollet** [comment]
Hi @FieteO and thanks for reporting this bug.

I have been able to reproduce the issue.

**Comment by nmengin** [comment]
Traefik Pilot doesn't exist anymore.
I close the issue accordingly.

Thanks @mloiseleur 🦅
