### ISSUE TITLE
Config Updates: Error in Go routine: reflect: slice index out of range

### ISSUE THREAD

**Issue by gkrizek** [traefik/traefik#8083]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Running Traefik with Redis as the backend. Updating the routes by writing keys into Redis for the given routes, services, and rules. I have 3 Traefik instances reading from Redis.

### What did you expect to see?

I expect all 3 Traefik instances to get the config updates in realtime and process them accordingly without error. If Traefik does hit an error I'd like it to continue trying to receive updates.

### What did you see instead?

1 out of the 3 Traefik instances hits a Go Routine Panic and then stops watching for updates. To fix it I have to just restart Traefik and it works as expected again. This has happened several times and it's always just 1 of the three that hits this issue.

Output of the panic:

```
{"entryPointName":"myentrypoint","level":"error","msg":"error while parsing rule : 1:1: expected operand, found 'EOF'","routerName":"myrouter@redis","time":"2021-04-20T11:52:51Z"}

{"level":"error","msg":"Error in Go routine: reflect: slice index out of range","time":"2021-04-20T11:54:09Z"}

{"level":"error","msg":"Stack: goroutine 95 [running]:\nruntime/debug.Stack(0x40000e2000, 0x21e7505, 0x17)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x88\ngithub.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x1bdd760, 0x2634b10)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:66 +0xac\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x22da000)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:56 +0x54\npanic(0x1bdd760, 0x2634b10)\n\t/usr/local/go/src/runtime/panic.go:969 +0x11c\nreflect.Value.Index(0x1b85280, 0x4001add060, 0x197, 0x7, 0x1bdd760, 0x4000b6d730, 0x198)\n\t/usr/local/go/src/reflect/value.go:946 +0x1e0\nreflect.deepValueEqual(0x1b85280, 0x4000a94100, 0x197, 0x1b85280, 0x4001add060, 0x197, 0x400119bc40, 0x8, 0x4002b5ca01)\n\t/usr/local/go/src/reflect/deepequal.go:98 +0x928\nreflect.deepValueEqual(0x1fa5f00, 0x4000a940c0, 0x199, 0x1fa5f00, 0x4001add020, 0x199, 0x400119bc40, 0x7, 0x0)\n\t/usr/local/go/src/reflect/deepequal.go:115 +0x774\nreflect.deepValueEqual(0x1d344e0, 0x4000a940c0, 0x16, 0x1d344e0, 0x4001add020, 0x16, 0x4000e57c40, 0x6, 0x16)\n\t/usr/local/go/src/reflect/deepequal.go:112 +0xec4\nreflect.deepValueEqual(0x1cf3600, 0x4001487830, 0x195, 0x1cf3600, 0x40028755b0, 0x195, 0x400119bc40, 0x5, 0x40014c1601)\n\t/usr/local/go/src/reflect/deepequal.go:133 +0xcf4\nreflect.deepValueEqual(0x1e375c0, 0x4001487830, 0x199, 0x1e375c0, 0x40028755b0, 0x199, 0x400119bc40, 0x4, 0x4001c48201)\n\t/usr/local/go/src/reflect/deepequal.go:115 +0x774\nreflect.deepValueEqual(0x1d34460, 0x4002053fc8, 0x196, 0x1d34460, 0x400234f5a8, 0x196, 0x4000e57c40, 0x3, 0x4001551901)\n\t/usr/local/go/src/reflect/deepequal.go:112 +0xec4\nreflect.deepValueEqual(0x1f3e9c0, 0x4002053fc0, 0x199, 0x1f3e9c0, 0x400234f5a0, 0x199, 0x400119bc40, 0x2, 0x0)\n\t/usr/local/go/src/reflect/deepequal.go:115 +0x774\nreflect.deepValueEqual(0x1d33660, 0x40022afcf0, 0x96, 0x1d33660, 0x40022afd10, 0x96, 0x40014c1c40, 0x1, 0x4001c85301)\n\t/usr/local/go/src/reflect/deepequal.go:112 +0xec4\nreflect.deepValueEqual(0x1e37200, 0x40022afce0, 0x99, 0x1e37200, 0x40022afd00, 0x99, 0x400119bc40, 0x0, 0x40014c1bf8)\n\t/usr/local/go/src/reflect/deepequal.go:115 +0x774\nreflect.DeepEqual(0x1e37200, 0x40022afce0, 0x1e37200, 0x40022afd00, 0x1)\n\t/usr/local/go/src/reflect/deepequal.go:210 +0x230\ngithub.com/containous/traefik/v2/pkg/server.(*ConfigurationWatcher).throttleProviderConfigReload(0x40003d87e0, 0x26e98c0, 0x40003e6500, 0x77359400, 0x400038b6e0, 0x4000210d80)\n\t/go/src/github.com/containous/traefik/pkg/server/configurationwatcher.go:222 +0x1e8\ngithub.com/containous/traefik/v2/pkg/server.(*ConfigurationWatcher).preLoadConfiguration.func1(0x26e98c0, 0x40003e6500)\n\t/go/src/github.com/containous/traefik/pkg/server/configurationwatcher.go:187 +0x50\ngithub.com/containous/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:36 +0x64\ngithub.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x22da000, 0x40008c36c0)\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:59 +0x50\ncreated by github.com/containous/traefik/v2/pkg/safe.GoWithRecover\n\t/go/src/github.com/containous/traefik/pkg/safe/routine.go:53 +0x44\n","time":"2021-04-20T11:54:09Z"}
```

Trying to read the stack trace it looks like it's failing on the `reflect.DeepEqual` check for the configurations:
https://github.com/traefik/traefik/blob/master/pkg/server/configurationwatcher.go#L228

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v2.2.1
Codename:     cheddar
Go version:   go1.14.15
Built:        2021-04-05_08:13:45PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```
traefik --api --api.dashboard --api.insecure --ping --entryPoints.ping.address=:9950 --ping.entryPoint=ping --entrypoints.one.address=:1111 --entrypoints.two.address=:2222 --entrypoints.three.address=:3333 --entrypoints.four.address=:4444 --entrypoints.five.address=:5555 --providers.redis.endpoints=localhost:6379 --providers.redis.rootkey=traefik --providers.file.filename=/etc/redis/dynamictls.yaml
```

 *Trying to make the stack trace more readable:*

```
Stack: goroutine 95 [running]:
runtime/debug.Stack(0x40000e2000, 0x21e7505, 0x17)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/containous/traefik/v2/pkg/safe.defaultRecoverGoroutine(0x1bdd760, 0x2634b10)
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:66 +0xac
github.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1.1(0x22da000)
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:56 +0x54
panic(0x1bdd760, 0x2634b10)
	/usr/local/go/src/runtime/panic.go:969 +0x11c
reflect.Value.Index(0x1b85280, 0x4001add060, 0x197, 0x7, 0x1bdd760, 0x4000b6d730, 0x198)
	/usr/local/go/src/reflect/value.go:946 +0x1e0
reflect.deepValueEqual(0x1b85280, 0x4000a94100, 0x197, 0x1b85280, 0x4001add060, 0x197, 0x400119bc40, 0x8, 0x4002b5ca01)
	/usr/local/go/src/reflect/deepequal.go:98 +0x928
reflect.deepValueEqual(0x1fa5f00, 0x4000a940c0, 0x199, 0x1fa5f00, 0x4001add020, 0x199, 0x400119bc40, 0x7, 0x0)
	/usr/local/go/src/reflect/deepequal.go:115 +0x774
reflect.deepValueEqual(0x1d344e0, 0x4000a940c0, 0x16, 0x1d344e0, 0x4001add020, 0x16, 0x4000e57c40, 0x6, 0x16)
	/usr/local/go/src/reflect/deepequal.go:112 +0xec4
reflect.deepValueEqual(0x1cf3600, 0x4001487830, 0x195, 0x1cf3600, 0x40028755b0, 0x195, 0x400119bc40, 0x5, 0x40014c1601)
	/usr/local/go/src/reflect/deepequal.go:133 +0xcf4
reflect.deepValueEqual(0x1e375c0, 0x4001487830, 0x199, 0x1e375c0, 0x40028755b0, 0x199, 0x400119bc40, 0x4, 0x4001c48201)
	/usr/local/go/src/reflect/deepequal.go:115 +0x774
reflect.deepValueEqual(0x1d34460, 0x4002053fc8, 0x196, 0x1d34460, 0x400234f5a8, 0x196, 0x4000e57c40, 0x3, 0x4001551901)
	/usr/local/go/src/reflect/deepequal.go:112 +0xec4
reflect.deepValueEqual(0x1f3e9c0, 0x4002053fc0, 0x199, 0x1f3e9c0, 0x400234f5a0, 0x199, 0x400119bc40, 0x2, 0x0)
	/usr/local/go/src/reflect/deepequal.go:115 +0x774
reflect.deepValueEqual(0x1d33660, 0x40022afcf0, 0x96, 0x1d33660, 0x40022afd10, 0x96, 0x40014c1c40, 0x1, 0x4001c85301)
	/usr/local/go/src/reflect/deepequal.go:112 +0xec4
reflect.deepValueEqual(0x1e37200, 0x40022afce0, 0x99, 0x1e37200, 0x40022afd00, 0x99, 0x400119bc40, 0x0, 0x40014c1bf8)
	/usr/local/go/src/reflect/deepequal.go:115 +0x774
reflect.DeepEqual(0x1e37200, 0x40022afce0, 0x1e37200, 0x40022afd00, 0x1)
	/usr/local/go/src/reflect/deepequal.go:210 +0x230
github.com/containous/traefik/v2/pkg/server.(*ConfigurationWatcher).throttleProviderConfigReload(0x40003d87e0, 0x26e98c0, 0x40003e6500, 0x77359400, 0x400038b6e0, 0x4000210d80)
	/go/src/github.com/containous/traefik/pkg/server/configurationwatcher.go:222 +0x1e8
github.com/containous/traefik/v2/pkg/server.(*ConfigurationWatcher).preLoadConfiguration.func1(0x26e98c0, 0x40003e6500)
	/go/src/github.com/containous/traefik/pkg/server/configurationwatcher.go:187 +0x50
github.com/containous/traefik/v2/pkg/safe.(*Pool).GoCtx.func1()
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:36 +0x64
github.com/containous/traefik/v2/pkg/safe.GoWithRecover.func1(0x22da000, 0x40008c36c0)
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:59 +0x50
created by github.com/containous/traefik/v2/pkg/safe.GoWithRecover
	/go/src/github.com/containous/traefik/pkg/safe/routine.go:53 +0x44
```

**Comment by ldez** [comment]
Hello,

could you try with the latest version (v2.4.8)?

**Comment by gkrizek** [comment]
I've been trying out v2.4.8 and it seems to be working. I'll continue to monitor...

Closing unless it pops back up
