### ISSUE TITLE
v2.5 - HTTP3 fails in POST request

### ISSUE THREAD

**Issue by melchor629** [traefik/traefik#8373]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

I enabled HTTP3 support for give it a try once after 2.5 is out. Quick testing I see everything works fine.

I have a Home Assistant instance behind traefik. When I access to the login page, the frontend sends a `POST` request to the HASS backend, but traefik fails giving an `500 Internal Server Error`, and HASS do not receive the request.

I have enabled Access Log but also tried without it enabled and also fails (see debug logs below).

### What did you see instead?

The request did not arrived to the backend, but traefik failed with an Internal Server Error, but just when using HTTP3. The same request through HTTP2 works perfectly.

### What version of Traefik are you using?

```
Version:      2.5.0
Codename:     livarot
Go version:   go1.17
Built:        2021-08-17T16:16:03Z
OS/Arch:      linux/arm64
```

Using docker in a Raspberry PI 4, `traefik:2.5` image.

### What is your environment & configuration?

```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: true

experimental:
  http3: true

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
    enableHTTP3: true
    http:
      tls:
        options: default
        certResolver: le

api:
  dashboard: true

log:
  level: INFO

accessLog:
  filePath: /dev/stderr

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefiknet
  file:
    directory: /etc/traefik/config
    watch: true

certificatesResolvers:
  le:
    acme:
      email: '...'
      storage: '/etc/traefik/acme/new-acme.json'
      httpChallenge:
        entryPoint: http
```

If applicable, the `docker-compose.yaml`:

```yaml
version: '3'

services:
  traefik:
    image: traefik:2.5
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./admin.users:/etc/traefik/admin.users:ro"
      - "./acme:/etc/traefik/acme"
      - "./config:/etc/traefik/config:ro"
      - "./htpasswd:/etc/traefik/htpasswd:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "traefiknet"
      #- "traefik_pubnet"
      - "dbs"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: on-failure

networks:
  traefiknet:
    external: true
```

### With Access Log enabled

```
level=error msg="Recovered from panic in HTTP handler [192.168.2.1:62061 - /auth/login_flow]: interface conversion: *accesslog.captureResponseWriter is not http.CloseNotifier: missing method CloseNotify" middlewareName=traefik-internal-recovery middlewareType=Recovery
level=error msg="Stack: goroutine 433 [running]:
github.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0xffff9585b828, 0x4000b1dcc0}, 0x4000a03000)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:46 +0x270
panic({0x2860ce0, 0x4000c0b6e0})
    /usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x224
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*responseModifier).CloseNotify(0x40001a3ae0)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/responsewriter.go:98 +0x40
net/http/httputil.(*ReverseProxy).ServeHTTP(0x4000293f40, {0x3392b20, 0x40001a3ae0}, 0x4000a03b00)
    /usr/local/golang/1.10.8/go/src/net/http/httputil/reverseproxy.go:224 +0x128
github.com/traefik/traefik/v2/pkg/middlewares/pipelining.(*pipelining).ServeHTTP(0x400071faf0, {0x3392b20, 0x40001a3ae0}, 0x4000a03b00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/pipelining/pipelining.go:34 +0x94
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddServiceFields({0x3392b20, 0x40001a3ae0}, 0x4000a03b00, {0x3361ac0, 0x400071faf0}, 0x400057cf40)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:47 +0x148
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x4000187b40, {0x3392b20, 0x40001a3ae0}, 0x4000a03b00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0x100
github.com/vulcand/oxy/roundrobin.(*RoundRobin).ServeHTTP(0x40001e3500, {0x3392b20, 0x40001a3ae0}, 0x4000a03a00)
    /home/semaphore/go/pkg/mod/github.com/vulcand/oxy@v1.3.0/roundrobin/rr.go:147 +0x558
github.com/traefik/traefik/v2/pkg/middlewares/emptybackendhandler.(*emptyBackend).ServeHTTP(0x400071fb50, {0x3392b20, 0x40001a3ae0}, 0x4000a03a00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/emptybackendhandler/empty_backend_handler.go:25 +0x154
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0x40008b9320, {0x3392b20, 0x40001a3ae0}, 0x4000a03a00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/forwarder.go:38 +0x4d0
github.com/traefik/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP.func1({0xffff9585b828, 0x4000b1dcc0}, 0x4000a03a00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/secure.go:53 +0x130
github.com/unrolled/secure.(*Secure).HandlerFuncWithNextForRequestOnly(0x4000c9b080, {0xffff9585b828, 0x4000b1dcc0}, 0x4000a03900, 0x4000c64db8)
    /home/semaphore/go/pkg/mod/github.com/unrolled/secure@v1.0.9/secure.go:233 +0x30c
github.com/traefik/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP({{0x3361c40, 0x40008b9320}, 0x4000c9b080, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...}}, ...)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/secure.go:52 +0x60
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*headers).ServeHTTP(0x40004cf3c0, {0xffff9585b828, 0x4000b1dcc0}, 0x4000a03900)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/headers.go:91 +0x4c
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0x40008b9470, {0xffff9585b828, 0x4000b1dcc0}, 0x4000a03900)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/wrapper.go:57 +0x130
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x4000187c00, {0xffff9585b828, 0x4000b1dcc0}, 0x4000a03900)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:38 +0x130
github.com/gorilla/mux.(*Router).ServeHTTP(0x4000723560, {0xffff9585b828, 0x4000b1dcc0}, 0x4000a03000)
    /home/semaphore/go/pkg/mod/github.com/containous/mux@v0.0.0-20181024131434-c33f32e26898/mux.go:133 +0x268
github.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x4000d22d20, {0xffff9585b828, 0x4000b1dcc0}, 0x4000a03000)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:32 +0x8c
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddOriginFields({0xffff9585b828, 0x4000b1dc80}, 0x4000a03000, {0x3361b00, 0x4000d22d20}, 0x400057cf40)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:55 +0x198
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x4000137a80, {0xffff9585b828, 0x4000b1dc80}, 0x4000a03000)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:36 +0x100
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0x4000289138, {0xffff9585b828, 0x4000b1dc80}, 0x4000a02f00, 0x4000c65620)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x5e8
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0xffff9585b828, 0x4000b1dc80}, 0x4000a02f00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x70
net/http.HandlerFunc.ServeHTTP(0x4000a66140, {0xffff9585b828, 0x4000b1dc80}, 0x4000a02f00)
    /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x40
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*Handler).ServeHTTP(0x400024a0c0, {0x3392520, 0x400057cf00}, 0x4000a02e00, {0x33681a0, 0x4000a66140})
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/logger.go:227 +0x1110
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.WrapHandler.func1.1({0x3392520, 0x400057cf00}, 0x4000a02e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/logger.go:71 +0x50
net/http.HandlerFunc.ServeHTTP(0x4000a66160, {0x3392520, 0x400057cf00}, 0x4000a02e00)
    /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x40
github.com/traefik/traefik/v2/pkg/server/router/tcp.(*Manager).buildEntryPointHandler.func1({0x3392520, 0x400057cf00}, 0x4000a02e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/tcp/router.go:194 +0x188
net/http.HandlerFunc.ServeHTTP(0x4000a67160, {0x3392520, 0x400057cf00}, 0x4000a02e00)
    /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x40
github.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4000289120, {0x3392520, 0x400057cf00}, 0x4000a02e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/handler_switcher.go:23 +0x70
github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0x4000114f00, {0x3392520, 0x400057cf00}, 0x4000a02e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/forwardedheaders/forwarded_header.go:183 +0xec
github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest.func2(0x4000114f50, 0x4000b62e2e, {0x33619c0, 0x4000114f00}, 0x400057cf00, 0x4000a02e00)
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:396 +0x80
github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest(0x4000114f50, {0x341dc00, 0x400089a000}, {0xffff9585b738, 0x4000a72960}, 0x40008a0060, 0x40006648a0)
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:397 +0xa98
github.com/lucas-clemente/quic-go/http3.(*Server).handleConn.func1(0x4000114f50, {0xffff95812240, 0x400089a000}, {0xffff9585b738, 0x4000a72960}, 0x40008a0060, {0x0, 0x0})
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:253 +0xcc
created by github.com/lucas-clemente/quic-go/http3.(*Server).handleConn
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:252 +0x1b4
" middlewareType=Recovery middlewareName=traefik-internal-recovery
```

### Without Access Log enabled

```
level=error msg="Recovered from panic in HTTP handler [192.168.2.1:61108 - /auth/login_flow]: interface conversion: *http3.responseWriter is not http.CloseNotifier: missing method CloseNotify" middlewareName=traefik-internal-recovery middlewareType=Recovery
level=error msg="Stack: goroutine 122 [running]:
github.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x3392520, 0x400098e8c0}, 0x4000ce5c00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:46 +0x270
panic({0x2860ce0, 0x400099eb40})
    /usr/local/golang/1.10.8/go/src/runtime/panic.go:1038 +0x224
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*responseModifier).CloseNotify(0x4000d2bc20)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/responsewriter.go:98 +0x40
net/http/httputil.(*ReverseProxy).ServeHTTP(0x4000d2adc0, {0x3392b20, 0x4000d2bc20}, 0x40009a6000)
    /usr/local/golang/1.10.8/go/src/net/http/httputil/reverseproxy.go:224 +0x128
github.com/traefik/traefik/v2/pkg/middlewares/pipelining.(*pipelining).ServeHTTP(0x4000ae5c40, {0x3392b20, 0x4000d2bc20}, 0x40009a6000)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/pipelining/pipelining.go:34 +0x94
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x4000babe80, {0x3392b20, 0x4000d2bc20}, 0x40009a6000)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:29 +0x16c
github.com/vulcand/oxy/roundrobin.(*RoundRobin).ServeHTTP(0x40001e8b60, {0x3392b20, 0x4000d2bc20}, 0x4000ce5f00)
    /home/semaphore/go/pkg/mod/github.com/vulcand/oxy@v1.3.0/roundrobin/rr.go:147 +0x558
github.com/traefik/traefik/v2/pkg/middlewares/emptybackendhandler.(*emptyBackend).ServeHTTP(0x4000ae5ca0, {0x3392b20, 0x4000d2bc20}, 0x4000ce5f00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/emptybackendhandler/empty_backend_handler.go:25 +0x154
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0x400050d500, {0x3392b20, 0x4000d2bc20}, 0x4000ce5f00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/forwarder.go:38 +0x4d0
github.com/traefik/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP.func1({0x3392520, 0x400098e8c0}, 0x4000ce5f00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/secure.go:53 +0x130
github.com/unrolled/secure.(*Secure).HandlerFuncWithNextForRequestOnly(0x4000cf8c60, {0x3392520, 0x400098e8c0}, 0x4000ce5e00, 0x4000995138)
    /home/semaphore/go/pkg/mod/github.com/unrolled/secure@v1.0.9/secure.go:233 +0x30c
github.com/traefik/traefik/v2/pkg/middlewares/headers.secureHeader.ServeHTTP({{0x3361c40, 0x400050d500}, 0x4000cf8c60, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, ...}, ...}}, ...)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/secure.go:52 +0x60
github.com/traefik/traefik/v2/pkg/middlewares/headers.(*headers).ServeHTTP(0x40000bb900, {0x3392520, 0x400098e8c0}, 0x4000ce5e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/headers/headers.go:91 +0x4c
github.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0x400050d6e0, {0x3392520, 0x400098e8c0}, 0x4000ce5e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/tracing/wrapper.go:57 +0x130
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x4000babf00, {0x3392520, 0x400098e8c0}, 0x4000ce5e00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:29 +0x16c
github.com/gorilla/mux.(*Router).ServeHTTP(0x4000d10ae0, {0x3392520, 0x400098e8c0}, 0x4000ce5c00)
    /home/semaphore/go/pkg/mod/github.com/containous/mux@v0.0.0-20181024131434-c33f32e26898/mux.go:133 +0x268
github.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x4000529530, {0x3392520, 0x400098e8c0}, 0x4000ce5c00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/recovery/recovery.go:32 +0x8c
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x4000d052c0, {0x3392520, 0x400098e8c0}, 0x4000ce5c00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/accesslog/field_middleware.go:29 +0x16c
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0x4000206018, {0x3392520, 0x400098e8c0}, 0x4000ce5b00, 0x4000b218f0)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x5e8
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x3392520, 0x400098e8c0}, 0x4000ce5b00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x70
net/http.HandlerFunc.ServeHTTP(0x4000ae68e0, {0x3392520, 0x400098e8c0}, 0x4000ce5b00)
    /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x40
github.com/traefik/traefik/v2/pkg/server/router/tcp.(*Manager).buildEntryPointHandler.func1({0x3392520, 0x400098e8c0}, 0x4000ce5b00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/server/router/tcp/router.go:194 +0x188
net/http.HandlerFunc.ServeHTTP(0x4000ae7920, {0x3392520, 0x400098e8c0}, 0x4000ce5b00)
    /usr/local/golang/1.10.8/go/src/net/http/server.go:2046 +0x40
github.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4000287ff0, {0x3392520, 0x400098e8c0}, 0x4000ce5b00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/handler_switcher.go:23 +0x70
github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0x40006ce960, {0x3392520, 0x400098e8c0}, 0x4000ce5b00)
    /home/semaphore/go/src/github.com/traefik/traefik/pkg/middlewares/forwardedheaders/forwarded_header.go:183 +0xec
github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest.func2(0x40006ce9b0, 0x4000b21e2e, {0x33619c0, 0x40006ce960}, 0x400098e8c0, 0x4000ce5b00)
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:396 +0x80
github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest(0x40006ce9b0, {0x341dc00, 0x4000dc8000}, {0xffff5d3aaed0, 0x4000a161e0}, 0x40006cdb00, 0x4000cdf8a8)
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:397 +0xa98
github.com/lucas-clemente/quic-go/http3.(*Server).handleConn.func1(0x40006ce9b0, {0xffff5d30c020, 0x4000dc8000}, {0xffff5d3aaed0, 0x4000a161e0}, 0x40006cdb00, {0x0, 0x0})
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:253 +0xcc
created by github.com/lucas-clemente/quic-go/http3.(*Server).handleConn
    /home/semaphore/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.22.0/http3/server.go:252 +0x1b4
" middlewareName=traefik-internal-recovery middlewareType=Recovery
```

### The request that fails

```sh
curl 'https://<redacted>/auth/login_flow' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0' \
  -H 'Accept: */*' \
  -H 'Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3' \
  --compressed \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  -H 'Origin: https://<redacted>' \
  -H 'DNT: 1' -H 'Alt-Used: <redacted>' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Referer: https://<redacted>/' \
  -H 'Connection: keep-alive' \
  -H 'TE: trailers' \
  --data-raw '{"client_id":"https://<redacted>/","handler":["homeassistant",null],"redirect_uri":"https://<redacted>/?auth_callback=1"}'
```

**Comment by traefiker** [comment]
Closed by #8374.
