### ISSUE TITLE
traefik memory continues to increase

### ISSUE THREAD

**Issue by heshengkai** [traefik/traefik#9211]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

traefik version 2.6.3
kubernetes version 1.21.7

traefik pod  memory continues to increase, maybe memory leak

Please help, thank you  very much.

### What did you see instead?

traefik pod  memory continues to increase, maybe memory leak.

### What version of Traefik are you using?

Version:      2.6.3
Codename:     rocamadour
Go version:     go1.17.8
Built:             2022-03-29T13:09:27Z
OS/Arch:      linux/amd64

### What is your environment & configuration?

args:
        - --global.checknewversion=false
        - --global.sendanonymoususage=false
        - --api=true
        - --api.insecure=true
        - --api.dashboard=true
        - --log.level=WARN
        - --log.filepath=/var/log/log.log
        - --accesslog.bufferingSize=100
        - --accesslog.format=json
        - --accesslog.filepath=/var/log/access.log
        - --accesslog.fields.headers.names.X-Forwarded-For=keep
        - --accesslog.fields.headers.names.X-Ruxit-Forwarded-For=keep
        - --accesslog.fields.headers.names.User-Agent=keep
        - --accesslog.fields.headers.names.Connect=keep
        - --accesslog.fields.headers.names.X-Real-Ip=keep
        - --entrypoints.http.Address=:80
        - --entrypoints.https.Address=:443
        - --entrypoints.admin.Address=:8087
        - --entryPoints.ping.address=:8085
        - --entrypoints.traefik.Address=127.0.0.1:8086
        - --entrypoints.https.http.tls=true
        - --ping.entryPoint=ping
        - --providers.http.tls.insecureskipverify=true
        - --entrypoints.https.proxyprotocol.insecure=true
        - --entrypoints.http.forwardedHeaders.insecure=true
        - --entrypoints.https.forwardedHeaders.insecure=true
        - --entrypoints.admin.forwardedHeaders.insecure=true
        - --providers.kubernetesingress.ingressclass=traefik-internet
        - --providers.kubernetescrd.ingressclass=traefik-internet
        - --providers.kubernetescrd.allowCrossNamespace=true
        - --providers.kubernetescrd.allowexternalnameservices=true
        - --providers.kubernetesingress.allowEmptyServices=true
        - --metrics.prometheus
        - --metrics.prometheus.addRoutersLabels=true
        - --metrics.prometheus.addentrypointslabels=true
        - --metrics.prometheus.addserviceslabels=true
        - --metrics.prometheus.entrypoint=traefik

### If applicable, please paste the log output in DEBUG level

{"level":"error","msg":"Error in Go routine: net/http: abort Handler","time":"2022-07-13T09:20:39+08:00"}
{"level":"error","msg":"Stack: goroutine 471317469 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x2f423e0, 0xc00011ea90})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:74 +0x35\npanic({0x2f423e0, 0xc00011ea90})\n\truntime/panic.go:1038 +0x215\nnet/http/httputil.(*ReverseProxy).ServeHTTP(0xc00605b9f0, {0x7f1af33cdec0, 0xc00a074430}, 0xc00687c700)\n\tnet/http/httputil/reverseproxy.go:348 +0xeba\ngithub.com/traefik/traefik/v2/pkg/middlewares/pipelining.(*pipelining).ServeHTTP(0xc00a752690, {0x7f1af33cdec0, 0xc00a074430}, 0xc00687c700)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/pipelining/pipelining.go:34 +0x6b\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddServiceFields({0x7f1af33cdec0, 0xc00a074430}, 0xc00687c700, {0x3f658c0, 0xc00a752690}, 0xc00a2e72c0)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:47 +0x110\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc004ce6800, {0x7f1af33cdec0, 0xc00a074430}, 0xc00c3c07a0)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:36 +0xd8\ngithub.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc0072a9500, {0x7f1af3448de0, 0xc00a074428}, 0xc00687c700)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:121 +0x722\ngithub.com/vulcand/oxy/roundrobin.(*RoundRobin).ServeHTTP(0xc0072a9650, {0x7f1af3448de0, 0xc00a074428}, 0xc00687c600)\n\tgithub.com/vulcand/oxy@v1.3.0/roundrobin/rr.go:147 +0x52c\ngithub.com/traefik/traefik/v2/pkg/middlewares/emptybackendhandler.(*emptyBackend).ServeHTTP(0xc00a752890, {0x7f1af3448de0, 0xc00a074428}, 0xc002598d80)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/emptybackendhandler/empty_backend_handler.go:25 +0xfd\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.(*forwarderMiddleware).ServeHTTP(0xc00a0d6fc0, {0x7f1af3448de0, 0xc00a074428}, 0xc00687c600)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/forwarder.go:38 +0x47d\ngithub.com/traefik/traefik/v2/pkg/middlewares/retry.(*retry).ServeHTTP.func1()\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/retry/retry.go:101 +0x46f\ngithub.com/traefik/traefik/v2/pkg/safe.OperationWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:78 +0x63\ngithub.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc00921a4c0, {0x3f89ec0, 0xc0049b4d00}, 0xc008e1ab58, {0x0, 0x0})\n\tgithub.com/cenkalti/backoff/v4@v4.1.1/retry.go:55 +0x12a\ngithub.com/cenkalti/backoff/v4.RetryNotify(...)\n\tgithub.com/cenkalti/backoff/v4@v4.1.1/retry.go:34\ngithub.com/traefik/traefik/v2/pkg/middlewares/retry.(*retry).ServeHTTP(0xc004ce6a40, {0x3f99488, 0xc00a2e7540}, 0xc00687c500)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/retry/retry.go:121 +0x3c5\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc00a0d7230, {0x3f99488, 0xc00a2e7540}, 0xc00687c500)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:57 +0x106\ngithub.com/vulcand/oxy/buffer.(*Buffer).ServeHTTP(0xc00605bcc0, {0x7f1af33cdec0, 0xc00a074418}, 0xc00687c400)\n\tgithub.com/vulcand/oxy@v1.3.0/buffer/buffer.go:281 +0x904\ngithub.com/traefik/traefik/v2/pkg/middlewares/buffering.(*buffer).ServeHTTP(0x3fcd100, {0x7f1af33cdec0, 0xc00a074418}, 0xc00d0a8f28)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/buffering/buffering.go:54 +0x27\ngithub.com/traefik/traefik/v2/pkg/middlewares/tracing.(*Wrapper).ServeHTTP(0xc00a0d7410, {0x7f1af33cdec0, 0xc00a074418}, 0xc00687c400)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/tracing/wrapper.go:57 +0x106\ngithub.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc003532460, {0x7f1af33cde70, 0xc00a074410}, 0xc00687c400)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:121 +0x722\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc004ce6c80, {0x7f1af33cde70, 0xc00a074410}, 0x2f9c120)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:38 +0xf6\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00a6e98c0, {0x7f1af33cde70, 0xc00a074410}, 0xc00687c300)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:141 +0x24c\ngithub.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0xc00841cbb8, {0x7f1af33cde70, 0xc00a074410}, 0x304b8a0)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x82\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.AddOriginFields({0x7f1af33cdec0, 0xc00a074400}, 0x365413a, {0x3f65900, 0xc003b8aa70}, 0xc00a2e72c0)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:55 +0x1a2\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0xc00bf29000, {0x7f1af33cdec0, 0xc00a074400}, 0xc0005b47c0)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:36 +0xd8\ngithub.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0xc006813880, {0x7f1af33cde70, 0xc00a0743f8}, 0xc00687c300)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:121 +0x722\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*Handler).ServeHTTP(0xc00070f080, {0x3fa6238, 0xc00d68afc0}, 0xc00c2eff00, {0x3f65880, 0xc006813880})\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/logger.go:227 +0xfa3\ngithub.com/traefik/traefik/v2/pkg/middlewares/accesslog.WrapHandler.func1.1({0x3fa6238, 0xc00d68afc0}, 0xc00d0a9700)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/accesslog/logger.go:71 +0x3b\nnet/http.HandlerFunc.ServeHTTP(0x90, {0x3fa6238, 0xc00d68afc0}, 0xc001db2000)\n\tnet/http/server.go:2047 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x4101a7, {0x3fa6238, 0xc00d68afc0}, 0x3f1c701)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/handler_switcher.go:23 +0x62\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0xc000663220, {0x3fa6238, 0xc00d68afc0}, 0xc00c2efe00, 0xc00d0a98f0)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x57b\ngithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x3fa6238, 0xc00d68afc0}, 0xc004c96d50)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x68\nnet/http.HandlerFunc.ServeHTTP(0xc00021c3c0, {0x3fa6238, 0xc00d68afc0}, 0x0)\n\tnet/http/server.go:2047 +0x2f\ngithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0xc00021c3c0, {0x3fa6238, 0xc00d68afc0}, 0xc00c2efe00)\n\tgithub.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders/forwarded_header.go:189 +0xca\ngolang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x3f657c0, 0xc00021c3c0}, 0xc0001eca40}, {0x3fa6238, 0xc00d68afc0}, 0xc00c2efe00)\n\tgolang.org/x/net@v0.0.0-20211209124913-491a49abca63/http2/h2c/h2c.go:104 +0x3e4\nnet/http.serverHandler.ServeHTTP({0x3f93fd8}, {0x3fa6238, 0xc00d68afc0}, 0xc00c2efe00)\n\tnet/http/server.go:2879 +0x43b\nnet/http.(*conn).serve(0xc00acf3360, {0x3fcd100, 0xc0008981b0})\n\tnet/http/server.go:1930 +0xb08\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3034 +0x4e8\n","time":"2022-07-13T09:20:39+08:00"}

**Comment by rtribotte** [comment]
Hello @heshengkai,

Thanks for your interest in Traefik!

The v2.6.3 is a bit old and maybe the bug has been fixed ever since.
Can you please try with the v2.8.1 in order to see if somehow the bug doesn't occur?

**Comment by igoooor** [comment]
I'm using traefik v2.8.1 on GKE v1.24.1-gke.1800 and I also experience this.
Here is a memory graph of my previous traefik pod (which I killed):
![Kubernetes___Compute_Resources___Pod_-_Grafana](https://user-images.githubusercontent.com/1036285/181016775-dcf443ce-f9df-4f44-9896-a25e60682126.png)
This was over multiple days as you see.

Now I restarted my pod in the morning, and here is the new pod's memory over a few hours:
![Kubernetes___Compute_Resources___Pod_-_Grafana-2](https://user-images.githubusercontent.com/1036285/181016899-5b5b2361-c145-4308-99e1-da63474f21e7.png)

Here are my container's arguments:
```
        - --serversTransport.maxIdleConnsPerHost=-1 # this is a recent attempt to fix some sporadic 502 from another issue
        - --api
        - --api.dashboard=true
        - --api.insecure=true
        - --metrics.prometheus=true
        - --metrics.prometheus.addRoutersLabels=true
        - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
        - --experimental.hub=true
        - --hub
        - --accesslog
        - --accesslog.format=json
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.Address=:443
        - --entrypoints.websecure.forwardedHeaders.insecure=true
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowExternalNameServices=true
        - --providers.kubernetescrd.allowCrossNamespace=true
        - --providers.kubernetesingress=true
        - --providers.kubernetesingress.allowExternalNameServices=true
        - --providers.kubernetesingress.ingressclass=traefik-cert-manager
        - --ping=true
```

**Comment by heshengkai** [comment]
@rtribotte thanks for your reply. @igoooor Feedback information， traefik 2.8.1  remains the same.
Here is a memory graph of my previous traefik pod (which I killed):
![1658886978077](https://user-images.githubusercontent.com/13656790/181143765-9f834968-23ff-472a-acbb-5704604d6388.png)

**Comment by kevinpollet** [comment]
Hello @heshengkai,

We saw that you have a `panic` in your logs, do you know why is this happening?

As this issue is quite complex to analyze without the env/infrastructure details,
could you share a simple reproducible case?

**Comment by kevinpollet** [comment]
Hello @igoooor,

Even if the memory consumption increase over time, the root cause may not be the same. 

Therefore, could you open a new issue?

As asked in https://github.com/traefik/traefik/issues/9211#issuecomment-1196394066, could you also provide a reproducible case and memory pprof in the issue details?

**Comment by heshengkai** [comment]
@kevinpollet Thank you for your method, Traefik serves as the edge route for the K8S cluster. I will observe the memory usage of my Traefik service and provide  memory allocation report in time.
[error.txt](https://github.com/traefik/traefik/files/9230271/error.txt)

**Comment by bluepuma77** [comment]
I have the same issue, Grafana shows my Traefik instances in Docker Swarm using 5GB of RAM each, continuously growing.

But when looking at `htop` or `docker stats --all --no-stream`, those instances look normal. So it might be an issue with the data used, most probably from `node-exporter` or `cadvisor`.

**Comment by rtribotte** [comment]
Hello @heshengkai,

We released the v2.8.4 and it brings a fix for the retry middleware: https://github.com/traefik/traefik/pull/9284.
After re-reading the issue it seems that it should help to solve this issue as well because it prevents the retry middleware to retry indefinitely when a panic occurs, can you give it a try?

**Comment by bluepuma77** [comment]
Just another note on the memory usage graph which seems to come from Grafana:

> You might think that memory utilization is easily tracked with `container_memory_usage_bytes`, however, this metric also includes cached (think filesystem cache) items that can be evicted under memory pressure. The better metric is `container_memory_working_set_bytes` as this is what the OOM killer is watching for.

Source: [stackoverflow](https://stackoverflow.com/questions/65428558/what-is-the-difference-between-container-memory-working-set-bytes-and-contain)
