### ISSUE TITLE
gRPC-Web middleware sends incorrect content-length to backend servers

### ISSUE THREAD

**Issue by CleverUnderDog** [traefik/traefik#9697]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am using [grpc-web](https://github.com/grpc/grpc-web) in my react frontend and [grpc-java](https://github.com/grpc/grpc-java) in my backend application. After seeing grpc-web support from Traefik I decided to give it a try and it worked flawlessly in the beginning.
After upgrading grpc-java from 1.41.0 to 1.51.0 I realised that in version 1.42.0 there was a internal change that started validating the content-length header.

### What did you see instead?

After upgrading the grpc-java version the proxied requests through the grpc-web middleware stopped working with the following error:
```
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception$StreamException: Received amount of data 22 does not match content-length header 32
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:153) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$ContentLength.increaseReceivedBytes(DefaultHttp2ConnectionDecoder.java:806) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.verifyContentLength(DefaultHttp2ConnectionDecoder.java:230) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.access$300(DefaultHttp2ConnectionDecoder.java:53) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:303) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onDataRead(DefaultHttp2ConnectionDecoder.java:691) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:250) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.52.1.jar:1.52.1]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

Here are some related issues that I found: https://github.com/grpc/grpc-java/issues/9019 and https://github.com/grpc/grpc/issues/29216

I have also tried to remove the content-length header with a header middleware but it did not made any difference.

### What version of Traefik are you using?

3.0.0-beta2

### What is your environment & configuration?

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: grpcweb
spec:
  grpcWeb:
    allowOrigins:
      - "*"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: remove-content-length-header
spec:
  headers:
    customRequestHeaders:
      Content-Length: "" # Removes
      content-length: "" # Removes
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    meta.helm.sh/release-name: backend
    meta.helm.sh/release-namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm
  name: grpc-ingress-tls
  namespace: dev
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`grpc-web.example.com`) && PathPrefix(`/Auth`)
    middlewares:
    - name: grpcweb
    - name: remove-content-length-header
    services:
    - name: auth
      port: 6565
      scheme: h2c

```

**Comment by CleverUnderDog** [comment]
I have done some further investigation. The content-length header should be removed according to the grpcweb handler [implementation](https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/wrapper.go#L296). Therefore it seems like there is another place where the content-length is set.

**Comment by CleverUnderDog** [comment]
So I have found the solution to this problem. We have to set the ContentLength on the request itself to -1 in order to get rid of the content-length header entirely.

I have a question regarding go and how to submit changes. Do I have to add the following change to this repository or to the dependency?
```go
req.Header.Del("content-length")
req.ContentLength = -1
```

**Comment by mpl** [comment]
@CleverUnderDog ok, thanks for letting us know that the problem is not in traefik.

Please feel free to reopen if you discover otherwise.

We're a bit confused about why you're making a PR on improbable-eng/grcp-web since you hadn't mentioned that repo before though. It it a dependency for your whole setup? if yes, is it a dependency for your react front-end, or for your java backend?

**Comment by CleverUnderDog** [comment]
@mpl your [grpcweb middleware](https://github.com/traefik/traefik/blob/master/pkg/middlewares/grpcweb/grpcweb.go) is based on improbable-eng/grcp-web implementation and therefore an update of this dependency will be required to resolve this issue in traefik.

I have already created a fork with a patch that can be used in go.mod in case the change is not going to be merged upstream (https://github.com/CleverUnderDog/grpc-web/tree/v0.15.1).

If you want I can create a PR with a replace directive so it is already included in traefik.

**Comment by mpl** [comment]
@CleverUnderDog yeah thanks, my bad, we just found out while you were answering. I was looking in the deps of traefik v2, where of course it does not exist.

For now, we'd rather not depend on a fork. But yeah, let's revisit that option later if we really need to.

Let's reopen that issue until the problem is actually fixed *somewhere*.

**Comment by CleverUnderDog** [comment]
@mpl I have checked the upstream repo and realised that it is in maintenance mode and probably won't get any updates.

> Please note that this repo is in maintenance mode, and we recommend users migrate to the official grpc-web client: https://github.com/grpc/grpc-web.

I will prepare a PR for traefik which includes my fork. I am running this change in production for 3 weeks without any incident regarding grpcweb functionality.

**Comment by CleverUnderDog** [comment]
@mpl is there any new information if this will make it in the next release of Traefik v3?

As expected there were no changes on the dependency upstream. We have been running the forked patch for 6 months now and haven't had any issues with grpc-web. We will also include an updated version to beta-3 and provide a pull request to this repository.

**Comment by ldez** [comment]
Hello @CleverUnderDog,

we (Traefik maintainers) will fork [improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web/), it's better if we own the fork.
After the creation of the fork, can you open a PR on it?

I will handle the fork tomorrow (Monday EU time zone).

**Comment by ldez** [comment]
the fork is ready https://github.com/traefik/grpc-web

**Comment by CleverUnderDog** [comment]
Hello @ldez,

It seems like I am not able to create a pull request onto your fork. In the beginning I thought this might be a cache issue with GitHub that did not sync your fork yet. But as of today I am still unable to create a pull request onto your fork.

**Comment by ldez** [comment]
During the creation of the PR, you have to choose our fork.

**Comment by CleverUnderDog** [comment]
That's exactly what I am trying to do:

<img width="946" alt="image" src="https://github.com/traefik/traefik/assets/37074703/2965d589-a537-455f-8817-228a38ae1447">

**Comment by ldez** [comment]
You have to fork our fork.

**Comment by ldez** [comment]
https://github.com/traefik/grpc-web/compare/master...CleverUnderDog:grpc-web:fix-wrong-content-length

**Comment by CleverUnderDog** [comment]
I have been able to create the pull request with the help of your link (https://github.com/traefik/grpc-web/pull/1).

I will close the original pull request for grpc-web and update the pull request to traefik (https://github.com/traefik/traefik/pull/9782).
